export const allQuestions = [
      {
          "question": "testing update",
          "answer": "test",
          "wrong_answer1": "npm create-react-app",
          "wrong_answer2": "npm create-react-app myReactApp",
          "wrong_answer3": "npx create-react-app",
          "topic_id": 1,
          "question_id": 1,
          "topic": "React",
          "text_link": "https://www.w3schools.com/REACT/DEFAULT.ASP",
          "video_link": "https://www.youtube.com/watch?v=hQAHSlTtcmY&ab_channel=WebDevSimplified",
          "interactive_link": "https://www.freecodecamp.org/news/tag/react/"
      },
      {
          "question": "Why should you avoid copying the values of props into a component's state?",
          "answer": "Because that would create two instances of the same state that could become out of sync",
          "wrong_answer1": "Because you want to allow data to flow back up to the parent",
          "wrong_answer2": "Because prop values cannot be stored in state",
          "wrong_answer3": "Because you should never mutate state",
          "topic_id": 1,
          "question_id": 4,
          "topic": "React",
          "text_link": "https://www.w3schools.com/REACT/DEFAULT.ASP",
          "video_link": "https://www.youtube.com/watch?v=hQAHSlTtcmY&ab_channel=WebDevSimplified",
          "interactive_link": "https://www.freecodecamp.org/news/tag/react/"
      },
      {
          "question": "What tool does React use to compile JSX?",
          "answer": "Babel",
          "wrong_answer1": "JSX Compiler",
          "wrong_answer2": "React Router",
          "wrong_answer3": "ReactDOM",
          "topic_id": 1,
          "question_id": 3,
          "topic": "React",
          "text_link": "https://www.w3schools.com/REACT/DEFAULT.ASP",
          "video_link": "https://www.youtube.com/watch?v=hQAHSlTtcmY&ab_channel=WebDevSimplified",
          "interactive_link": "https://www.freecodecamp.org/news/tag/react/"
      },
      {
          "question": "What is the children prop?",
          "answer": "A property that lets you nest components in other components",
          "wrong_answer1": "A property that adds child values to state",
          "wrong_answer2": "A property that lets you pass data to child components",
          "wrong_answer3": "A property that lets you set an object as a property",
          "topic_id": 1,
          "question_id": 2,
          "topic": "React",
          "text_link": "https://www.w3schools.com/REACT/DEFAULT.ASP",
          "video_link": "https://www.youtube.com/watch?v=hQAHSlTtcmY&ab_channel=WebDevSimplified",
          "interactive_link": "https://www.freecodecamp.org/news/tag/react/"
      },
      {
          "question": "How do you insert a comment in a CSS file?",
          "answer": "/* comment */",
          "wrong_answer1": "//coment",
          "wrong_answer2": "** coment **",
          "wrong_answer3": "/ ' coment ' /",
          "topic_id": 2,
          "question_id": 8,
          "topic": "HTML/CSS",
          "text_link": "https://www.w3schools.com/html/",
          "video_link": "https://www.youtube.com/watch?v=G3e-cpL7ofc",
          "interactive_link": "https://www.freecodecamp.org/learn/2022/responsive-web-design/"
      },
      {
          "question": "What is the correct HTML element used to draw graphics on a web page?",
          "answer": "<canvas>",
          "wrong_answer1": "<graphic>",
          "wrong_answer2": "< !! >",
          "wrong_answer3": "<svg>",
          "topic_id": 2,
          "question_id": 7,
          "topic": "HTML/CSS",
          "text_link": "https://www.w3schools.com/html/",
          "video_link": "https://www.youtube.com/watch?v=G3e-cpL7ofc",
          "interactive_link": "https://www.freecodecamp.org/learn/2022/responsive-web-design/"
      },
      {
          "question": "What is the correct HTML element for inserting a line break?",
          "answer": "<br>",
          "wrong_answer1": "<lb>",
          "wrong_answer2": "<newline>",
          "wrong_answer3": "<//>",
          "topic_id": 2,
          "question_id": 6,
          "topic": "HTML/CSS",
          "text_link": "https://www.w3schools.com/html/",
          "video_link": "https://www.youtube.com/watch?v=G3e-cpL7ofc",
          "interactive_link": "https://www.freecodecamp.org/learn/2022/responsive-web-design/"
      },
      {
          "question": "How do you declare a global variable in CSS?",
          "answer": ":root { var: value }",
          "wrong_answer1": "global { var: value}",
          "wrong_answer2": "!!{var: value}",
          "wrong_answer3": "var: value",
          "topic_id": 2,
          "question_id": 5,
          "topic": "HTML/CSS",
          "text_link": "https://www.w3schools.com/html/",
          "video_link": "https://www.youtube.com/watch?v=G3e-cpL7ofc",
          "interactive_link": "https://www.freecodecamp.org/learn/2022/responsive-web-design/"
      },
      {
          "question": "How do you round the number 7.25, to the nearest integer?",
          "answer": "Math.round(7.25)",
          "wrong_answer1": "Math.rnd(7.25)",
          "wrong_answer2": "round(7.25)",
          "wrong_answer3": "rnd(7.25)",
          "topic_id": 3,
          "question_id": 12,
          "topic": "JS",
          "text_link": "https://www.tutorialspoint.com/javascript/index.htm",
          "video_link": "https://www.youtube.com/watch?v=W6NZfCO5SIk",
          "interactive_link": "https://www.codecademy.com/learn/introduction-to-javascript"
      },
      {
          "question": "How does a WHILE loop start?",
          "answer": "while (i <= 10)",
          "wrong_answer1": "while (i <= 10, i++)",
          "wrong_answer2": "while i = 1 to 10",
          "wrong_answer3": "while (i <= 10; i++)",
          "topic_id": 3,
          "question_id": 11,
          "topic": "JS",
          "text_link": "https://www.tutorialspoint.com/javascript/index.htm",
          "video_link": "https://www.youtube.com/watch?v=W6NZfCO5SIk",
          "interactive_link": "https://www.codecademy.com/learn/introduction-to-javascript"
      },
      {
          "question": "How do you write \"Hello World\" in an alert box?",
          "answer": "alert(\"Hello World\");",
          "wrong_answer1": "msgBox(\"Hello World\");",
          "wrong_answer2": "msg(\"Hello World\");",
          "wrong_answer3": "alertBox(\"Hello World\");",
          "topic_id": 3,
          "question_id": 10,
          "topic": "JS",
          "text_link": "https://www.tutorialspoint.com/javascript/index.htm",
          "video_link": "https://www.youtube.com/watch?v=W6NZfCO5SIk",
          "interactive_link": "https://www.codecademy.com/learn/introduction-to-javascript"
      },
      {
          "question": "Inside which HTML element do we put the JavaScript?",
          "answer": "<script>",
          "wrong_answer1": "<scripting>",
          "wrong_answer2": "<javascript>",
          "wrong_answer3": "<js>",
          "topic_id": 3,
          "question_id": 9,
          "topic": "JS",
          "text_link": "https://www.tutorialspoint.com/javascript/index.htm",
          "video_link": "https://www.youtube.com/watch?v=W6NZfCO5SIk",
          "interactive_link": "https://www.codecademy.com/learn/introduction-to-javascript"
      },
      {
          "question": "Which SQL statement is used to create a database table called 'Customers'?",
          "answer": "CREATE TABLE Customers",
          "wrong_answer1": "CREATE DB Customers",
          "wrong_answer2": "CREATE DATABASE TAB Customers",
          "wrong_answer3": "CREATE DATABASE TABLE Customers \r\n",
          "topic_id": 4,
          "question_id": 16,
          "topic": "SQL",
          "text_link": "https://www.w3schools.com/sql/",
          "video_link": "https://www.youtube.com/watch?v=p3qvj9hO_Bo",
          "interactive_link": "https://sqlbolt.com/"
      },
      {
          "question": "With SQL, how do you select a column named \"FirstName\" from a table named \"Persons\"?",
          "answer": "SELECT FirstName FROM Persons",
          "wrong_answer1": "EXTRACT FirstName FROM Persons",
          "wrong_answer2": "SELECT Persons.FirstName",
          "wrong_answer3": "SELECT First.Name FROM Person",
          "topic_id": 4,
          "question_id": 15,
          "topic": "SQL",
          "text_link": "https://www.w3schools.com/sql/",
          "video_link": "https://www.youtube.com/watch?v=p3qvj9hO_Bo",
          "interactive_link": "https://sqlbolt.com/"
      },
      {
          "question": "What is the most common type of join?",
          "answer": "INNER JOIN",
          "wrong_answer1": "JOINED",
          "wrong_answer2": "INSIDE JOIN",
          "wrong_answer3": "JOINED TABLE",
          "topic_id": 4,
          "question_id": 14,
          "topic": "SQL",
          "text_link": "https://www.w3schools.com/sql/",
          "video_link": "https://www.youtube.com/watch?v=p3qvj9hO_Bo",
          "interactive_link": "https://sqlbolt.com/"
      },
      {
          "question": "What does SQL stand for?",
          "answer": "Structured Query Language",
          "wrong_answer1": "Strong Question Language \r\n",
          "wrong_answer2": "Structured Question Language",
          "wrong_answer3": "Strong Query Language",
          "topic_id": 4,
          "question_id": 13,
          "topic": "SQL",
          "text_link": "https://www.w3schools.com/sql/",
          "video_link": "https://www.youtube.com/watch?v=p3qvj9hO_Bo",
          "interactive_link": "https://sqlbolt.com/"
      }
  ];